<a href="https://colab.research.google.com/github/razzacktiger/2024-react-beginner/blob/Final-Project/Array_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

# Lists

In [4]:
My_list = [[1,2,3,4,5], [3, 4, 5, 6, 7]]
My_list


[[1, 2, 3, 4, 5], [3, 4, 5, 6, 7]]

# Numpy Arrays

In [5]:
np1 = np.random.rand(3,4) # 3 by 4 array with random values
np1

array([[0.09652275, 0.79193973, 0.86241262, 0.97374085],
       [0.79992831, 0.40637943, 0.51517788, 0.75166621],
       [0.42391368, 0.91032607, 0.62196883, 0.02574662]])

In [13]:
# data type of np1
np1.dtype


dtype('float64')

# Tensors

In [6]:
tensor2d = torch.randn(3,4)
tensor2d

tensor([[-0.4469,  0.9350,  0.4664, -0.4551],
        [ 1.7535,  2.9719, -1.1343, -0.1785],
        [ 1.2658,  1.5546,  0.8258,  0.1334]])

In [9]:
tensor3d = torch.zeros(2, 3, 4)
tensor3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0965, 0.7919, 0.8624, 0.9737],
        [0.7999, 0.4064, 0.5152, 0.7517],
        [0.4239, 0.9103, 0.6220, 0.0257]], dtype=torch.float64)

In [14]:
# type of tensor
my_tensor.dtype

torch.float64